---
title: "DEEP: Future Fit"
author: "by Jess"
format:
    revealjs:
        theme: [solarized, custom.scss]
        slideNumber: true
        show-slide-number: all
        #reference-location: document
        #logo: images/logo.png
        footer: "https://deep-future-fit.netlify.app/"
        chalkboard:
            theme: whiteboard
        #code-annotations: hover
        css: styles.css
        mermaid:
          theme: default
        highlight-style: github
        #highlight-style: monochrome
        #logo: qr-code.png
        #multiplex: true
editor:
    render-on-save: true

---
# Review

::: {.notes}
blooket + discussion
:::

# Systems Programming

## Systems

- Operating Systems
- Embedded Systems
- Microcontrollers

## Computer Hardware

Every computer has a central processing unit (CPU) that executes instructions.

Types of CPU architectures:

- ARM (Raspberry Pi, Apple Silicon, Qualcomm Snapdragon)
- x86 (Intel/AMD CPUs)
- RISC-V

::: {.fragment .fade-in}
What is an architecture?
:::

## Bluetooth Low-Energy (BLE)
Wireless communication designed for low-power, short-range communication.

What applications or use cases is BLE good for?

::: {.fragment .fade-in}
- Fitness trackers
- Healthcare devices
- Smart sensors
- Internet of Things (IoT) devices
:::

::: {.notes}
compare with bluetooth
:::

## BLE Modes

Advertising: the device broadcasts its presence to nearby devices.

<br>

Connection: Bidirectional communication between central and peripheral devices.

## Services and Characteristics

Labels to organize BLE communication:

- Services: a group of related characteristics that provide a specific functionality.
- Characteristics: a single value that can be read or written by the central device.

## Profiles
BLE protocol issues standard profiles that simplify development.

For example:

- Battery Service (0x180F)
    - Battery Level Characteristic (0x2A19)
- Heart Rate Service (0x180D)
    - Heart Rate Measurement Characteristic (0x2A37)


## Arduino
- Arduino is a microcontroller that allows you to control devices and process simple tasks 
- Can receive inputs and send outputs 

## Arduino

- **3.3V and 5V Pins**
  - Provide power to sensors and other circuit components
  - Output a constant voltage of 3.3 V or 5 V

- **GND (Ground)**
  - Reference point for the circuit
  - Provides the return path for current

---

## Arduino
- **Analog Pins (A0–A5)**
  - Can be configured as inputs or outputs
  - Used to read sensor values or send digital signals
  - Can read a continuous range of input values (`analogRead()`)

- **Digital Pins (0–13)**
  - Can be set as inputs or outputs
  - Used to read or send signals
  - Can only be HIGH or LOW (on or off)
  - Pins marked with `~` also support PWM (`analogWrite()`)

---
## Arduino
- **VIN**
  - Input voltage pin used to power the Arduino from an external source

- **USB Port**
  - Used to upload code
  - Powers the board
  - Enables communication with the computer

- **Reset Button**
  - Restarts the Arduino program from the beginning

## Circuits
TODO

## Programming an Arduino
Program Setup 
    - void setup()
        Where you can set your pins 
        Runs once to configure your hardware
    - void loop()
        Main code that will run on loop 

## Programming an Arduino- Assigning Pins
- `pinMode()`
- `digitalRead()`
- `digitalWrite()`
- `analogRead()`
- `analogWrite()`

- `Serial.begin()`
- `Serial.print()`
- `Serial.println()`

## Number Representations

- Decimal (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
- Binary (0, 1)
- Octal (0, 1, 2, 3, 4, 5, 6, 7)
- Hexadecimal (0-9, A, B, C, D, E, F)

::: {.notes}
hand out worksheet, not important to complete, can skip
:::

# 2 in binary?

::: {.notes}
take out ipad and show them how to compute values
:::

## Converting to Decimal (from non-Decimal)

1. Multiply each digit by its base raised to the power of its position (from
right to left, starting at 0).
2. Sum all the values obtained.

::: {.notes}
work through some examples with them
:::

## Converting to Binary (from Decimal)

1. Divide the decimal number by the base of the target system.
2. Write down the remainder.
3. Repeat the division with the quotient until the quotient becomes zero.
4. Read the remainders in reverse order (from last to first). This is the equivalent number in the target
base.

::: {.notes}
work through some examples with them
:::


## Bitwise Operators
```{.c}
// Bitwise operators: &, |, ^, ~, <<, >>
printf("  5 & 3  = %d\n", 5 & 3);
printf("  5 | 3  = %d\n", 5 | 3);
printf("  5 << 1 = %d\n\n", 5 << 1);
```

What is the output?

```
5 & 3  = 1
5 | 3  = 7
5 << 1 = 10
```

::: {.notes}
- (0101 & 0011 = 0001)
- (0101 | 0011 = 0111)
- (0101 << 1 = 1010)
:::

# Tutorial

# Javascript


## Introduction
- JavaScript is the **programming language for web apps**.
    - ... but also for desktop apps, mobile apps, and server-side scripting.
- It can:
  - Calculate and manipulate data.
  - Update and modify HTML and CSS.
- Used to create interactive websites.

## JS Playground

<br>

[RunJS](https://runjs.app/play)

<br>

Feel free to use any javascript playground!


## Variables
JavaScript variables store data.

### `let`

Used when the value may change.

```js
let score = 10;
score = 20;
```

### `const`

Used when the variable should not be reassigned.

```js
const score = 10;
score = 20; // Error
```

Once assigned, a `const` variable cannot change to another value.




## Printing Output

### `console.log()`

```js
console.log("Hello");
```

Output:

```
Hello
```

### Multiple Values

```js
let a = 5;
let b = 10;

console.log(a, b);
```

Output:

```
5 10
```




## Operations: Arithmetic Operators

```js
let a = 10;
let b = 3;
```

| Operation | Expression | Result |
|-----------|------------|--------|
| Addition | `a + b` | 13 |
| Subtraction | `a - b` | 7 |
| Multiplication | `a * b` | 30 |
| Division | `a / b` | 3.333... |
| Modulus (Remainder) | `a % b` | 1 |
| Exponentiation | `a ** b` | 1000 |



## Operations:

### Assignment Operators

```js
let x = 5;

x += 2;   // 7
x -= 1;   // 6
x *= 3;   // 18
x /= 2;   // 9
```

### Comparison Operators

```js
5 > 3;   // true
5 < 3;   // false
5 >= 5;  // true
5 <= 4;  // false
```

Comparison operators return either `true` or `false`.


## Operations: Double vs Triple Equals

#### Double Equals (`==`)

Performs type conversion, only value matters.

```js
5 == "5";      // true
true == 1;     // true
false == 0;    // true
```

#### Triple Equals (`===`)

Checks both value and type.

```js
5 === 5;     // true
5 === "5";   // false
```

> With `===`, both the value and type must match.







## Functions

Instead of repeating:

```js
console.log("Hello");
console.log("Hello");
```

You can define the function once and call repeatedly:

```js
function sayHello() {
  console.log("Hello");
}
```

```js
sayHello();
sayHello();
...
```

Output:

```
Hello
Hello
```

## Parameters & Arguments

```js
function greet(name) {
  console.log("Hello " + name);
}
```

Usage:

```js
greet("Rita");
greet("Saniya");
```

Output:

```
Hello Rita
Hello Saniya
```

- Parameter: `name`
- Argument: `"Rita"` or `"Saniya"`

## Functions as Variables

```js
function square(num) {
  return num * num;
}
```
Can also be written as...

```js
const square = function(num) {
  return num * num;
};

console.log(square(5));
```

Output:

```
25
```

Functions can be stored as variables.

## Arrow Functions

An even shorter way to write functions.

```js
const square = function(num) {
  return num * num;
};
```

Can also be written as...

```js
const square = (num) => {
  return num * num;
};
```

And as...

```js
const square = num => num * num;
```

All three are equivalent.

## Callback Functions

A callback is a function passed into another function.

```js
function runCallback(callback) {
  callback();
}

function sayHello() {
  console.log("Hello");
}

runCallback(sayHello);
```

Output:

```
Hello
```
`sayHello` is a function passed as an *argument* to `runCallback` and `runCallback` calls it inside its definition.

## Arrays


```js
const nums = [10, 20, 30];
```


| Index | 0 | 1 | 2 |
|-------|---|---|---|
| Value | 10 | 20 | 30 |

Access elements:

```js
console.log(nums[0]); // 10
console.log(nums[2]); // 30
```

## Array Functions: forEach()

Meaning: Do something for every item in the array.

```js
const nums = [1, 2, 3];

nums.forEach(num => console.log(num));
```

What is the output?

::: {.fragment .fade-in}
```
1
2
3
```
:::

## Array Functions: map()

Create a new array by transforming every item.

```js
const nums = [1, 2, 3, 4];

const squares = nums.map(num => num * num);
console.log(squares);
```

What is the result?

::: {.fragment .fade-in}
```
[1, 4, 9, 16]
```
:::

## Array Functions: push()

Add something to the end of the array.

```js
const nums = [1, 2, 3];
nums.push(4);
console.log(nums);
```

What is the result?

::: {.fragment .fade-in}
```
[1, 2, 3, 4]
```
:::

## Array Functions: pop()

Remove the last item from the array and returns the removed item.

```js
const nums = [1, 2, 3, 4];

const popped = nums.pop();
console.log(popped);
console.log(nums);
```

What is the output?

::: {.fragment .fade-in}
```
4
[1, 2, 3]
```
:::

## Strings
A string is a sequence of characters enclosed by '' or "".

```js
const word = "hello";
```

Like arrays, characters are accessed by index:

```js
console.log(word[0]); // h
console.log(word[4]); // o
```
Strings are immutable

```js
word[0] = "H";
console.log(word); // "hello"
```

This does **not** change the string.

Finding the string length:

```js
console.log(word.length); // 5
```

## Objects

Like structs in C, objects allows us to group related information together.

```js
const student = {
  name: "Rita",
  age: 19,
  major: "Electrical Engineering"
};
```

Access information using dot notation (`.`):

```js
console.log(student.name); // Rita
console.log(student.age);  // 19
```

## Object Destructuring

Object destructuring is a shortcut that lets you take values from an object and directly turn them into variables.

Instead of:

```js
const name = student.name; // breaking into separate variables
const age = student.age;
```

We can write this:

```js
const { name, age } = student;

console.log(name); // Rita
console.log(age);  // 19
```

# Tutorial
